[package]
name = "better-resource-monitor"
version = "1.1.6"
description = "A lightweight menu bar and tray system monitor"
authors = ["Alex Pedersen <hello@alexpedersen.dev>"]
edition = "2021"
default-run = "better-resource-monitor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "better_resource_monitor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "better-resource-monitor"
path = "src/main.rs"


[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", default-features = false, features = ["tray-icon", "wry"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-single-instance = "2"
tauri-plugin-store = "2"
serde_json = "1"
sysinfo = { version = "0.39.3", features = ["apple-app-store"] }
image = { version = "0.25", default-features = false, features = ["png"] }
rusttype = "0.9"
tray-icon = "0.24.1"
font-kit = "0.14"
resvg = { version = "0.47", default-features = false }
sys-locale = "0.3"

[features]
default = []
app-store = []

# macOS-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-foundation-sys = "0.8"
libc = "0.2"
objc2 = "0.6.3"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSActionCell", "NSButton", "NSButtonCell", "NSCell", "NSControl", "NSResponder", "NSStatusBarButton", "NSStatusItem", "NSView"] }
objc2-foundation = { version = "0.3.2", features = ["NSBundle", "NSString"] }
objc2-service-management = "0.3.2"

# Linux-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
nvml-wrapper = "0.12"

[dev-dependencies]

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false

[patch.crates-io]
plist = { git = "https://github.com/ebarnard/rust-plist", rev = "0a2f9e79fe4b" }
